(define-module (wlroots utils)
  #:use-module (system foreign)
  #:use-module (wlroots config)
  #:export (ffi:int wlr->pointer wlr->procedure))
(define ffi:int int)
(define (wlr->pointer name)
  (dynamic-func name (dynamic-link %libwlroots)))
(define (wlr->procedure return name params)
  (let ((ptr (wlr->pointer name)))
    (pointer->procedure return ptr params)))
