(define-module (gwwm user)
  #:use-module (wlroots)
  #:use-module (gwwm client)
  #:use-module (gwwm commands)
  #:use-module (gwwm config)
  #:use-module (gwwm i18n)
  #:use-module (gwwm keyboard)
  #:use-module (gwwm keymap)
  #:use-module (gwwm monitor)
  #:use-module (gwwm pointer)
  #:use-module (gwwm popup)
  #:use-module (gwwm touch)
  #:use-module (gwwm utils ref)
  #:use-module (gwwm utils srfi-215)
  #:use-module (gwwm utils)
  #:use-module (gwwm)
  #:use-module (oop goops describe)
  #:use-module (oop goops)
  #:use-module (oop goops)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-189)
  #:use-module (srfi srfi-19)
  #:use-module (srfi srfi-2)
  #:use-module (srfi srfi-26)
  #:use-module (srfi srfi-71)
  #:use-module (util572 box)
  #:duplicates (merge-accessors merge-generics replace warn-override-core warn last)  )
