(define-module (gwwm color)
  #:use-module (oop goops))

(define-class <color> ())
(define-class <rgb-color> (<color>)
  (r #:init-keyword #:r #:accessor color-r)
  (g #:init-keyword #:g #:accessor color-g)
  (b #:init-keyword #:b #:accessor color-b))
(define-class <rgba-color> (<rgb-color>)
  (a #:init-keyword #:a #:accessor color-a))
;; (define-method (initialize <color> initargs)
;;   (apply next-method initargs))
(define-method (make-color r g b)
  (make <rgb-color> #:r r #:g g #:b b))
(define-method (make-color r g b a)
  (make <rgba-color> #:r r #:g g #:b b #:a a))
