(define-module (gwwm commands)
  #:use-module (wlroots backend session)
  #:export (spawn))
(define (spawn program . args)
  (when (= (primitive-fork) 0)
    (dup2 (port->fdes (current-error-port))
          (port->fdes (current-output-port)))
    (setsid)
    (apply execlp program program args)))
