(add-to-load-path (pk 'a(dirname(dirname (current-filename)))))
(define-module (gwwm init)
  #:use-module (system repl server)
  #:use-module (wayland)
  #:use-module (srfi srfi-1)
  )
(define-values (program-name arguments) (car+cdr (program-arguments)))
(define keyboard-pass-hook (make-hook 1))
(define shutdown-hook (make-hook 1))
(add-hook! shutdown-hook (lambda (a) (pk 'shutdown-now!)))
(spawn-server (make-tcp-server-socket))
