SOURCES= %D%/../gwwm.scm\
		%D%/color.scm	\
		%D%/config.scm  \
		%D%/monitor.scm \
		%D%/client.scm \
		%D%/keymap.scm \
		%D%/keybind.scm \
		%D%/keys.scm \
		%D%/commands.scm
NOCOMP_SOURCES= %D%/startup.scm
